// This file was generated by the cargo-build script.

const ASCII_HEX_DIGIT_CHUNK_SIZE : usize = 32;
const ASCII_HEX_DIGIT_COLUMN_BITS : usize = 1;
const ASCII_HEX_DIGIT_INDEX_LEN : usize = 5;
const ASCII_HEX_DIGIT_INDEX_BITS : usize = 2;

const ASCII_HEX_DIGIT_INDEX_BYTE_OFFSET : usize = 12;

const ASCII_HEX_DIGIT_DATA: [u8; 15] = [
    // Column table
      0,  0,  0,  0,  0,  0,255,  3,126,  0,  0,  0,
    // Index table
    164,  0,
    // Padding to handle unaligned word reads.
      0,
];

/// Get the AsciiHexDigit attribute for a Unicode code-point.
///
/// # Arguments
///  - `code_point` A code-point in the form of a rust `char`.
///
/// # Returns
/// bool value
#[must_use] pub const fn get_ascii_hex_digit(code_point: char) -> bool
{
    const INDEX_MASK : usize = (1 << ASCII_HEX_DIGIT_INDEX_BITS) - 1;
    const COLUMN_MASK : usize = 1;

    let code_point_value = code_point as usize;
    let code_point_lo = code_point_value % ASCII_HEX_DIGIT_CHUNK_SIZE;
    let mut code_point_hi = code_point_value / ASCII_HEX_DIGIT_CHUNK_SIZE;
    if code_point_hi > ASCII_HEX_DIGIT_INDEX_LEN - 1 {
        code_point_hi = ASCII_HEX_DIGIT_INDEX_LEN - 1;
    }

    let index_offset = code_point_hi * ASCII_HEX_DIGIT_INDEX_BITS;
    let index_byte_offset = index_offset / 8;
    let index_bit_offset = index_offset % 8;
    let mut index: usize = 0;
    index |= (ASCII_HEX_DIGIT_DATA[ASCII_HEX_DIGIT_INDEX_BYTE_OFFSET + index_byte_offset + 1] as usize) << 8;
    index |= (ASCII_HEX_DIGIT_DATA[ASCII_HEX_DIGIT_INDEX_BYTE_OFFSET + index_byte_offset + 0] as usize) << 0;
    index >>= index_bit_offset;
    index &= INDEX_MASK;

    let column_offset = (index * ASCII_HEX_DIGIT_CHUNK_SIZE + code_point_lo) * ASCII_HEX_DIGIT_COLUMN_BITS;
    let column_byte_offset = column_offset / 8;
    let column_bit_offset = column_offset % 8;

    let mut value: usize = 0;
    value |= (ASCII_HEX_DIGIT_DATA[column_byte_offset + 0] as usize) << 0;
    value >>= column_bit_offset;
    value &= COLUMN_MASK;

    return match value {
        0 => false,
        _ => true,
    };
}

#[cfg(all(test, not(debug_assertions)))]
#[test]
fn ascii_hex_digit_full_coverage()
{
    for c in '\u{0000}'..='\u{d7ff}' {
        let _ = get_ascii_hex_digit(c);
    }
    for c in '\u{e000}'..='\u{10ffff}' {
        let _ = get_ascii_hex_digit(c);
    }
}

