// This file was generated by the cargo-build script.

const PATTERN_SYNTAX_CHUNK_SIZE : usize = 128;
const PATTERN_SYNTAX_COLUMN_BITS : usize = 1;
const PATTERN_SYNTAX_INDEX_LEN : usize = 510;
const PATTERN_SYNTAX_INDEX_BITS : usize = 4;

const PATTERN_SYNTAX_INDEX_BYTE_OFFSET : usize = 192;

const PATTERN_SYNTAX_DATA: [u8; 448] = [
    // Column table
      0,  0,  0,  0,254,255,  0,252,  1,  0,  0,120,  1,  0,  0,120,  0,  0,  0,  0,254, 90, 67,136,  0,  0,128,  0,  0,  0,128,  0,
      0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,255,255,255,  0,255,127,254,255,239,127,  0,  0,  0,  0,
      0,  0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,
    255,255,255,255,255,255,255,255,255,255,255,255,  0,  0,  0,  0,255,255,255,255,255,255,255,255,255,255,255,255,255,255, 63,  0,
      0,  0,240,255,255,255,255,255,255,255,255,255,255,255,255,255, 14,255,255,255,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,192,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 96,  0,  0,  0,  0,  0,  0,  0,
    // Index table
     16, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     35, 66, 85, 85, 38, 85, 85,135, 85, 85, 85, 85, 34, 34, 37, 34, 41, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,
     34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 42, 43,
    // Padding to handle unaligned word reads.
      0,
];

/// Get the PatternSyntax attribute for a Unicode code-point.
///
/// # Arguments
///  - `code_point` A code-point in the form of a rust `char`.
///
/// # Returns
/// bool value
#[must_use] pub const fn get_pattern_syntax(code_point: char) -> bool
{
    const INDEX_MASK : usize = (1 << PATTERN_SYNTAX_INDEX_BITS) - 1;
    const COLUMN_MASK : usize = 1;

    let code_point_value = code_point as usize;
    let code_point_lo = code_point_value % PATTERN_SYNTAX_CHUNK_SIZE;
    let mut code_point_hi = code_point_value / PATTERN_SYNTAX_CHUNK_SIZE;
    if code_point_hi > PATTERN_SYNTAX_INDEX_LEN - 1 {
        code_point_hi = PATTERN_SYNTAX_INDEX_LEN - 1;
    }

    let index_offset = code_point_hi * PATTERN_SYNTAX_INDEX_BITS;
    let index_byte_offset = index_offset / 8;
    let index_bit_offset = index_offset % 8;
    let mut index: usize = 0;
    index |= (PATTERN_SYNTAX_DATA[PATTERN_SYNTAX_INDEX_BYTE_OFFSET + index_byte_offset + 1] as usize) << 8;
    index |= (PATTERN_SYNTAX_DATA[PATTERN_SYNTAX_INDEX_BYTE_OFFSET + index_byte_offset + 0] as usize) << 0;
    index >>= index_bit_offset;
    index &= INDEX_MASK;

    let column_offset = (index * PATTERN_SYNTAX_CHUNK_SIZE + code_point_lo) * PATTERN_SYNTAX_COLUMN_BITS;
    let column_byte_offset = column_offset / 8;
    let column_bit_offset = column_offset % 8;

    let mut value: usize = 0;
    value |= (PATTERN_SYNTAX_DATA[column_byte_offset + 0] as usize) << 0;
    value >>= column_bit_offset;
    value &= COLUMN_MASK;

    return match value {
        0 => false,
        _ => true,
    };
}

