// This file was generated by the cargo-build script.

const REGIONAL_INDICATOR_CHUNK_SIZE : usize = 256;
const REGIONAL_INDICATOR_COLUMN_BITS : usize = 1;
const REGIONAL_INDICATOR_INDEX_LEN : usize = 499;
const REGIONAL_INDICATOR_INDEX_BITS : usize = 1;

const REGIONAL_INDICATOR_INDEX_BYTE_OFFSET : usize = 64;

const REGIONAL_INDICATOR_DATA: [u8; 128] = [
    // Column table
      0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,192,255,255,255,
    // Index table
      0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
      0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,
    // Padding to handle unaligned word reads.
      0,
];

/// Get the RegionalIndicator attribute for a Unicode code-point.
///
/// # Arguments
///  - `code_point` A code-point in the form of a rust `char`.
///
/// # Returns
/// bool value
#[must_use] pub const fn get_regional_indicator(code_point: char) -> bool
{
    const INDEX_MASK : usize = (1 << REGIONAL_INDICATOR_INDEX_BITS) - 1;
    const COLUMN_MASK : usize = 1;

    let code_point_value = code_point as usize;
    let code_point_lo = code_point_value % REGIONAL_INDICATOR_CHUNK_SIZE;
    let mut code_point_hi = code_point_value / REGIONAL_INDICATOR_CHUNK_SIZE;
    if code_point_hi > REGIONAL_INDICATOR_INDEX_LEN - 1 {
        code_point_hi = REGIONAL_INDICATOR_INDEX_LEN - 1;
    }

    let index_offset = code_point_hi * REGIONAL_INDICATOR_INDEX_BITS;
    let index_byte_offset = index_offset / 8;
    let index_bit_offset = index_offset % 8;
    let mut index: usize = 0;
    index |= (REGIONAL_INDICATOR_DATA[REGIONAL_INDICATOR_INDEX_BYTE_OFFSET + index_byte_offset + 1] as usize) << 8;
    index |= (REGIONAL_INDICATOR_DATA[REGIONAL_INDICATOR_INDEX_BYTE_OFFSET + index_byte_offset + 0] as usize) << 0;
    index >>= index_bit_offset;
    index &= INDEX_MASK;

    let column_offset = (index * REGIONAL_INDICATOR_CHUNK_SIZE + code_point_lo) * REGIONAL_INDICATOR_COLUMN_BITS;
    let column_byte_offset = column_offset / 8;
    let column_bit_offset = column_offset % 8;

    let mut value: usize = 0;
    value |= (REGIONAL_INDICATOR_DATA[column_byte_offset + 0] as usize) << 0;
    value >>= column_bit_offset;
    value &= COLUMN_MASK;

    return match value {
        0 => false,
        _ => true,
    };
}

